// <auto-generated />
using System;
using Inspection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inspection.Data.Migrations
{
    [DbContext(typeof(InspectionContext))]
    [Migration("20200206105231_262020351")]
    partial class _262020351
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inspection.Data.Entities.Application", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Application");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Tenant"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("FormBuilder");
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilderQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<int>("FormBuilderId");

                    b.Property<bool>("ISMultiSelect");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsMandatory");

                    b.Property<bool>("IsNotified");

                    b.Property<bool?>("IsScored");

                    b.Property<string>("Key");

                    b.Property<int?>("MaxScore");

                    b.Property<int>("ResponseType");

                    b.Property<int?>("Scored");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<string>("Text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderId");

                    b.ToTable("FormBuilderQuestions");
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilderQuestionsResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<int>("FormBuilderQuestionsId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("MaxScore");

                    b.Property<string>("ResponseText");

                    b.Property<int>("ResponseType");

                    b.Property<int>("Scored");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderQuestionsId");

                    b.ToTable("FormBuilderQuestionsResponse");
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("FormBuilderType");
                });

            modelBuilder.Entity("Inspection.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int>("RoleType");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Admin",
                            RoleType = 1
                        });
                });

            modelBuilder.Entity("Inspection.Data.Entities.RoleRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<string>("ControllerId");

                    b.Property<string>("ControllerRightId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("RoleId");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleRight");
                });

            modelBuilder.Entity("Inspection.Data.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<string>("Domain");

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<Guid>("Guid");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("Inspection.Data.Entities.TenantApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationId");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantApplication");
                });

            modelBuilder.Entity("Inspection.Data.Entities.User", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EditTime");

                    b.Property<string>("EditUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.Property<int?>("TenantId")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "inspecionAdmin",
                            IsDeleted = false,
                            Password = "07e63ef0386c1bf691ea22f8b3c4c04d",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilder", b =>
                {
                    b.HasOne("Inspection.Data.Entities.FormBuilderType", "FormBuilderType")
                        .WithMany("FormBuilder")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilderQuestions", b =>
                {
                    b.HasOne("Inspection.Data.Entities.FormBuilder", "FormBuilder")
                        .WithMany("FormBuilderQuestions")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inspection.Data.Entities.FormBuilderQuestionsResponse", b =>
                {
                    b.HasOne("Inspection.Data.Entities.FormBuilderQuestions", "FormBuilderQuestions")
                        .WithMany("FormBuilderQuestionsResponse")
                        .HasForeignKey("FormBuilderQuestionsId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inspection.Data.Entities.RoleRight", b =>
                {
                    b.HasOne("Inspection.Data.Entities.Role", "Role")
                        .WithMany("RoleRights")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inspection.Data.Entities.TenantApplication", b =>
                {
                    b.HasOne("Inspection.Data.Entities.Application", "Application")
                        .WithMany("TenantApplications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Inspection.Data.Entities.Tenant", "Tenant")
                        .WithMany("TenantApplications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inspection.Data.Entities.User", b =>
                {
                    b.HasOne("Inspection.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
